<h1><center>L&T LTFS Dataset</center></h1>

Question: How can we say our predictions will work for new data?

<h2>Data columns descriptions</h2>

disbursed_amoun -

<h2>Importing the required libraries</h2>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

<h2>Reading and understanding the dataset file</h2>

In [2]:
df = pd.read_csv("./data/train.csv", index_col = 0)

In [3]:
df.shape    # other similar methods - df.ndims, df.size

(233154, 40)

In [4]:
df.head()    # df.sample for single randomly chosen row

,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,Date.of.Birth,Employment.Type,DisbursalDate,...,SEC.SANCTIONED.AMOUNT,SEC.DISBURSED.AMOUNT,PRIMARY.INSTAL.AMT,SEC.INSTAL.AMT,NEW.ACCTS.IN.LAST.SIX.MONTHS,DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS,AVERAGE.ACCT.AGE,CREDIT.HISTORY.LENGTH,NO.OF_INQUIRIES,loan_default
UniqueID,,,,,,,,,,,,,,,,,,,,,
420825,50578,58400,89.55,67,22807,45,1441,01-01-84,Salaried,03-08-18,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
537409,47145,65550,73.23,67,22807,45,1502,31-07-85,Self employed,26-09-18,...,0,0,1991,0,0,1,1yrs 11mon,1yrs 11mon,0,1
417566,53278,61360,89.63,67,22807,45,1497,24-08-85,Self employed,01-08-18,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
624493,57513,66113,88.48,67,22807,45,1501,30-12-93,Self employed,26-10-18,...,0,0,31,0,0,0,0yrs 8mon,1yrs 3mon,1,1
539055,52378,60300,88.39,67,22807,45,1495,09-12-77,Self employed,26-09-18,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,1,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 233154 entries, 420825 to 630213
Data columns (total 40 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   disbursed_amount                     233154 non-null  int64
 1   asset_cost                           233154 non-null  int64
 2   ltv                                  233154 non-null  float64
 3   branch_id                            233154 non-null  int64
 4   supplier_id                          233154 non-null  int64
 5   manufacturer_id                      233154 non-null  int64
 6   Current_pincode_ID                   233154 non-null  int64
 7   Date.of.Birth                        233154 non-null  object
 8   Employment.Type                      225493 non-null  object
 9   DisbursalDate                        233154 non-null  object
 10  State_ID                             233154 non-null  int64
 11  Employee_code_ID                     233154 non-null  int64
 12  MobileNo_Avl_Flag                    233154 non-null  int64
 13  Aadhar_flag                          233154 non-null  int64
 14  PAN_flag                             233154 non-null  int64
 15  VoterID_flag                         233154 non-null  int64
 16  Driving_flag                         233154 non-null  int64
 17  Passport_flag                        233154 non-null  int64
 18  PERFORM_CNS.SCORE                    233154 non-null  int64
 19  PERFORM_CNS.SCORE.DESCRIPTION        233154 non-null  object
 20  PRI.NO.OF.ACCTS                      233154 non-null  int64
 21  PRI.ACTIVE.ACCTS                     233154 non-null  int64
 22  PRI.OVERDUE.ACCTS                    233154 non-null  int64
 23  PRI.CURRENT.BALANCE                  233154 non-null  int64
 24  PRI.SANCTIONED.AMOUNT                233154 non-null  int64
 25  PRI.DISBURSED.AMOUNT                 233154 non-null  int64
 26  SEC.NO.OF.ACCTS                      233154 non-null  int64
 27  SEC.ACTIVE.ACCTS                     233154 non-null  int64
 28  SEC.OVERDUE.ACCTS                    233154 non-null  int64
 29  SEC.CURRENT.BALANCE                  233154 non-null  int64
 30  SEC.SANCTIONED.AMOUNT                233154 non-null  int64
 31  SEC.DISBURSED.AMOUNT                 233154 non-null  int64
 32  PRIMARY.INSTAL.AMT                   233154 non-null  int64
 33  SEC.INSTAL.AMT                       233154 non-null  int64
 34  NEW.ACCTS.IN.LAST.SIX.MONTHS         233154 non-null  int64
 35  DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS  233154 non-null  int64
 36  AVERAGE.ACCT.AGE                     233154 non-null  object
 37  CREDIT.HISTORY.LENGTH                233154 non-null  object
 38  NO.OF_INQUIRIES                      233154 non-null  int64
 39  loan_default                         233154 non-null  int64
dtypes: float64(1), int64(33), object(6)
memory usage: 72.9+ MB

df.info() gets the null values and dtypes in one go.<br><br>
No null values except for Employment type. We see in last line that there are 33 int columns, 1 float column (ltv - this is a ratio term)<br>
Datetimes are read as object dtype = Python dtype string. We will want to convert these object types to other dtypes to use for plotting<br><br>
We can also load the data with<a href="https://stackoverflow.com/questions/21269399/datetime-dtypes-in-pandas-read-csv"> parse dates</a> option. <mark>(To try later)</mark>

In [6]:
# For statistics of all non-object dtype data
df.describe()

,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,State_ID,Employee_code_ID,MobileNo_Avl_Flag,...,SEC.OVERDUE.ACCTS,SEC.CURRENT.BALANCE,SEC.SANCTIONED.AMOUNT,SEC.DISBURSED.AMOUNT,PRIMARY.INSTAL.AMT,SEC.INSTAL.AMT,NEW.ACCTS.IN.LAST.SIX.MONTHS,DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS,NO.OF_INQUIRIES,loan_default
count,233154.000000,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.0,...,233154.000000,2.331540e+05,2.331540e+05,2.331540e+05,2.331540e+05,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000
mean,54356.993528,7.586507e+04,74.746530,72.936094,19638.635035,69.028054,3396.880247,7.262243,1549.477148,1.0,...,0.007244,5.427793e+03,7.295923e+03,7.179998e+03,1.310548e+04,3.232684e+02,0.381833,0.097481,0.206615,0.217071
std,12971.314171,1.894478e+04,11.456636,69.834995,3491.949566,22.141304,2238.147502,4.482230,975.261278,0.0,...,0.111079,1.702370e+05,1.831560e+05,1.825925e+05,1.513679e+05,1.555369e+04,0.955107,0.384439,0.706498,0.412252
min,13320.000000,3.700000e+04,10.030000,1.000000,10524.000000,45.000000,1.000000,1.000000,1.000000,1.0,...,0.000000,-5.746470e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,47145.000000,6.571700e+04,68.880000,14.000000,16535.000000,48.000000,1511.000000,4.000000,713.000000,1.0,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
50%,53803.000000,7.094600e+04,76.800000,61.000000,20333.000000,86.000000,2970.000000,6.000000,1451.000000,1.0,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
75%,60413.000000,7.920175e+04,83.670000,130.000000,23000.000000,86.000000,5677.000000,10.000000,2362.000000,1.0,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.999000e+03,0.000000e+00,0.000000,0.000000,0.000000,0.000000
max,990572.000000,1.628992e+06,95.000000,261.000000,24803.000000,156.000000,7345.000000,22.000000,3795.000000,1.0,...,8.000000,3.603285e+07,3.000000e+07,3.000000e+07,2.564281e+07,4.170901e+06,35.000000,20.000000,36.000000,1.000000

In [7]:
# This is superfluous, as df.info() does this and more
# df.dtypes

In [8]:
# Checking for null values in each column
df.isnull().sum()

disbursed_amount                          0
asset_cost                                0
ltv                                       0
branch_id                                 0
supplier_id                               0
manufacturer_id                           0
Current_pincode_ID                        0
Date.of.Birth                             0
Employment.Type                        7661
DisbursalDate                             0
State_ID                                  0
Employee_code_ID                          0
MobileNo_Avl_Flag                         0
Aadhar_flag                               0
PAN_flag                                  0
VoterID_flag                              0
Driving_flag                              0
Passport_flag                             0
PERFORM_CNS.SCORE                         0
PERFORM_CNS.SCORE.DESCRIPTION             0
PRI.NO.OF.ACCTS                           0
PRI.ACTIVE.ACCTS                          0
PRI.OVERDUE.ACCTS                         0
PRI.CURRENT.BALANCE                       0
PRI.SANCTIONED.AMOUNT                     0
PRI.DISBURSED.AMOUNT                      0
SEC.NO.OF.ACCTS                           0
SEC.ACTIVE.ACCTS                          0
SEC.OVERDUE.ACCTS                         0
SEC.CURRENT.BALANCE                       0
SEC.SANCTIONED.AMOUNT                     0
SEC.DISBURSED.AMOUNT                      0
PRIMARY.INSTAL.AMT                        0
SEC.INSTAL.AMT                            0
NEW.ACCTS.IN.LAST.SIX.MONTHS              0
DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS       0
AVERAGE.ACCT.AGE                          0
CREDIT.HISTORY.LENGTH                     0
NO.OF_INQUIRIES                           0
loan_default                              0
dtype: int64

Note the null values in Employment Type

<h2>Object type columns</h2>

In [9]:
df.loc[:, df.dtypes == object].head()

,Date.of.Birth,Employment.Type,DisbursalDate,PERFORM_CNS.SCORE.DESCRIPTION,AVERAGE.ACCT.AGE,CREDIT.HISTORY.LENGTH
UniqueID,,,,,,
420825,01-01-84,Salaried,03-08-18,No Bureau History Available,0yrs 0mon,0yrs 0mon
537409,31-07-85,Self employed,26-09-18,I-Medium Risk,1yrs 11mon,1yrs 11mon
417566,24-08-85,Self employed,01-08-18,No Bureau History Available,0yrs 0mon,0yrs 0mon
624493,30-12-93,Self employed,26-10-18,L-Very High Risk,0yrs 8mon,1yrs 3mon
539055,09-12-77,Self employed,26-09-18,No Bureau History Available,0yrs 0mon,0yrs 0mon

<h3>1. Employment Type</h3>

In [10]:
# Get rows where Employment Type has Nan value
empty_Employment = df[df['Employment.Type'].isnull()]['Employment.Type']
print(empty_Employment)

UniqueID
525234    NaN
637252    NaN
584433    NaN
515149    NaN
547112    NaN
         ...
494458    NaN
419420    NaN
553774    NaN
594901    NaN
563437    NaN
Name: Employment.Type, Length: 7661, dtype: object

In [11]:
# Find percentage of rows where Employment type is nan
Nan_percent = df['Employment.Type'].isnull().sum()*100/len(df)
Nan_percent

3.2858110948128703

In [12]:
df['Employment.Type'].unique()

array(['Salaried', 'Self employed', nan], dtype=object)

If we want to play around with this column's data, we will need to change this to numerical values.<br><br> 
Like categories:<br>
1: 'Salary'<br>
2: 'Self employed'<br>
3: nan<br>
Can use the replace method for this.

In [13]:
df['Employment.Type.Numeric'] = df['Employment.Type'].replace({'Salaried': 1, 'Self employed': 2, np.nan: 3})

In [14]:
df.head()

,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,Date.of.Birth,Employment.Type,DisbursalDate,...,SEC.DISBURSED.AMOUNT,PRIMARY.INSTAL.AMT,SEC.INSTAL.AMT,NEW.ACCTS.IN.LAST.SIX.MONTHS,DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS,AVERAGE.ACCT.AGE,CREDIT.HISTORY.LENGTH,NO.OF_INQUIRIES,loan_default,Employment.Type.Numeric
UniqueID,,,,,,,,,,,,,,,,,,,,,
420825,50578,58400,89.55,67,22807,45,1441,01-01-84,Salaried,03-08-18,...,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0,1
537409,47145,65550,73.23,67,22807,45,1502,31-07-85,Self employed,26-09-18,...,0,1991,0,0,1,1yrs 11mon,1yrs 11mon,0,1,2
417566,53278,61360,89.63,67,22807,45,1497,24-08-85,Self employed,01-08-18,...,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0,2
624493,57513,66113,88.48,67,22807,45,1501,30-12-93,Self employed,26-10-18,...,0,31,0,0,0,0yrs 8mon,1yrs 3mon,1,1,2
539055,52378,60300,88.39,67,22807,45,1495,09-12-77,Self employed,26-09-18,...,0,0,0,0,0,0yrs 0mon,0yrs 0mon,1,1,2

In [15]:
# Employment numeric type has no null values as they are replaced by 3.
# Can manipulate accordingly later
df.isnull().sum()

disbursed_amount                          0
asset_cost                                0
ltv                                       0
branch_id                                 0
supplier_id                               0
manufacturer_id                           0
Current_pincode_ID                        0
Date.of.Birth                             0
Employment.Type                        7661
DisbursalDate                             0
State_ID                                  0
Employee_code_ID                          0
MobileNo_Avl_Flag                         0
Aadhar_flag                               0
PAN_flag                                  0
VoterID_flag                              0
Driving_flag                              0
Passport_flag                             0
PERFORM_CNS.SCORE                         0
PERFORM_CNS.SCORE.DESCRIPTION             0
PRI.NO.OF.ACCTS                           0
PRI.ACTIVE.ACCTS                          0
PRI.OVERDUE.ACCTS                         0
PRI.CURRENT.BALANCE                       0
PRI.SANCTIONED.AMOUNT                     0
PRI.DISBURSED.AMOUNT                      0
SEC.NO.OF.ACCTS                           0
SEC.ACTIVE.ACCTS                          0
SEC.OVERDUE.ACCTS                         0
SEC.CURRENT.BALANCE                       0
SEC.SANCTIONED.AMOUNT                     0
SEC.DISBURSED.AMOUNT                      0
PRIMARY.INSTAL.AMT                        0
SEC.INSTAL.AMT                            0
NEW.ACCTS.IN.LAST.SIX.MONTHS              0
DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS       0
AVERAGE.ACCT.AGE                          0
CREDIT.HISTORY.LENGTH                     0
NO.OF_INQUIRIES                           0
loan_default                              0
Employment.Type.Numeric                   0
dtype: int64

<h3>2: Date of Birth, 3: Disbursal Date</h3>

<ol>
    <li>https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html</li>
    <li>https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html ---> date_parser </li>
</ol>

In [16]:
df['Date.of.Birth.datetime'] = pd.to_datetime(df['Date.of.Birth'], format = '%d-%m-%y')

In [17]:
df['DisbursalDate.datetime'] = df['DisbursalDate'].apply(lambda x: datetime.strptime(x, '%d-%m-%y'))

In [18]:
df.head()

,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,Date.of.Birth,Employment.Type,DisbursalDate,...,SEC.INSTAL.AMT,NEW.ACCTS.IN.LAST.SIX.MONTHS,DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS,AVERAGE.ACCT.AGE,CREDIT.HISTORY.LENGTH,NO.OF_INQUIRIES,loan_default,Employment.Type.Numeric,Date.of.Birth.datetime,DisbursalDate.datetime
UniqueID,,,,,,,,,,,,,,,,,,,,,
420825,50578,58400,89.55,67,22807,45,1441,01-01-84,Salaried,03-08-18,...,0,0,0,0yrs 0mon,0yrs 0mon,0,0,1,1984-01-01,2018-08-03
537409,47145,65550,73.23,67,22807,45,1502,31-07-85,Self employed,26-09-18,...,0,0,1,1yrs 11mon,1yrs 11mon,0,1,2,1985-07-31,2018-09-26
417566,53278,61360,89.63,67,22807,45,1497,24-08-85,Self employed,01-08-18,...,0,0,0,0yrs 0mon,0yrs 0mon,0,0,2,1985-08-24,2018-08-01
624493,57513,66113,88.48,67,22807,45,1501,30-12-93,Self employed,26-10-18,...,0,0,0,0yrs 8mon,1yrs 3mon,1,1,2,1993-12-30,2018-10-26
539055,52378,60300,88.39,67,22807,45,1495,09-12-77,Self employed,26-09-18,...,0,0,0,0yrs 0mon,0yrs 0mon,1,1,2,1977-12-09,2018-09-26

In [19]:
# Check null values to make sure all dates were parsed and formatted
df.isnull().sum()

disbursed_amount                          0
asset_cost                                0
ltv                                       0
branch_id                                 0
supplier_id                               0
manufacturer_id                           0
Current_pincode_ID                        0
Date.of.Birth                             0
Employment.Type                        7661
DisbursalDate                             0
State_ID                                  0
Employee_code_ID                          0
MobileNo_Avl_Flag                         0
Aadhar_flag                               0
PAN_flag                                  0
VoterID_flag                              0
Driving_flag                              0
Passport_flag                             0
PERFORM_CNS.SCORE                         0
PERFORM_CNS.SCORE.DESCRIPTION             0
PRI.NO.OF.ACCTS                           0
PRI.ACTIVE.ACCTS                          0
PRI.OVERDUE.ACCTS                         0
PRI.CURRENT.BALANCE                       0
PRI.SANCTIONED.AMOUNT                     0
PRI.DISBURSED.AMOUNT                      0
SEC.NO.OF.ACCTS                           0
SEC.ACTIVE.ACCTS                          0
SEC.OVERDUE.ACCTS                         0
SEC.CURRENT.BALANCE                       0
SEC.SANCTIONED.AMOUNT                     0
SEC.DISBURSED.AMOUNT                      0
PRIMARY.INSTAL.AMT                        0
SEC.INSTAL.AMT                            0
NEW.ACCTS.IN.LAST.SIX.MONTHS              0
DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS       0
AVERAGE.ACCT.AGE                          0
CREDIT.HISTORY.LENGTH                     0
NO.OF_INQUIRIES                           0
loan_default                              0
Employment.Type.Numeric                   0
Date.of.Birth.datetime                    0
DisbursalDate.datetime                    0
dtype: int64

In [20]:
# https://stackoverflow.com/questions/29206612/difference-between-data-type-datetime64ns-and-m8ns
df['Date.of.Birth.datetime'].dtype
# np.dtype('datetime64[ns]') == np.dtype('<M8[ns]')

dtype('<M8[ns]')

In [21]:
# Extracting only the rows where date time parsing gives year > 2021
df[df['Date.of.Birth.datetime'].dt.year > 2021]['Date.of.Birth']

UniqueID
510980    01-06-68
440293    02-08-68
501823    01-06-66
460555    01-06-64
517611    01-01-67
            ...
608319    13-08-63
602689    15-11-63
450782    16-01-64
626823    25-01-67
613161    15-06-63
Name: Date.of.Birth, Length: 19866, dtype: object

In [22]:
df[df['DisbursalDate.datetime'].dt.year > 2021]['DisbursalDate']

Series([], Name: DisbursalDate, dtype: object)

<h4>Explanation for above behavior</h4><br>
<a href = 'https://stackoverflow.com/questions/37766353/pandas-to-datetime-parsing-wrong-year'>Cutoff year</a> in python datetime library
<p>Below '31-Dec-68' --> 2068 <br>
   Above '1-Jan-69' --> 1968
</p>

<h3>4: PERFORM_CNS.SCORE.DESCRIPTION</h3>

In [23]:
# 20 unique values
df['PERFORM_CNS.SCORE.DESCRIPTION'].unique()

array(['No Bureau History Available', 'I-Medium Risk', 'L-Very High Risk',
       'A-Very Low Risk',
       'Not Scored: Not Enough Info available on the customer',
       'D-Very Low Risk', 'M-Very High Risk', 'B-Very Low Risk',
       'C-Very Low Risk', 'E-Low Risk', 'H-Medium Risk', 'F-Low Risk',
       'K-High Risk',
       'Not Scored: No Activity seen on the customer (Inactive)',
       'Not Scored: Sufficient History Not Available',
       'Not Scored: No Updates available in last 36 months', 'G-Low Risk',
       'J-High Risk', 'Not Scored: Only a Guarantor',
       'Not Scored: More than 50 active Accounts found'], dtype=object)

<h3>5: AVERAGE.ACCT.AGE, 6: CREDIT.HISTORY.LENGTH</h3>

In [24]:
df['AVERAGE.ACCT.AGE'].head()

UniqueID
420825     0yrs 0mon
537409    1yrs 11mon
417566     0yrs 0mon
624493     0yrs 8mon
539055     0yrs 0mon
Name: AVERAGE.ACCT.AGE, dtype: object

In [25]:
df['AVERAGE.ACCT.AGE'].str.split()

UniqueID
420825     [0yrs, 0mon]
537409    [1yrs, 11mon]
417566     [0yrs, 0mon]
624493     [0yrs, 8mon]
539055     [0yrs, 0mon]
              ...
626432     [1yrs, 9mon]
606141     [0yrs, 6mon]
613658     [0yrs, 0mon]
548084     [0yrs, 0mon]
630213     [0yrs, 0mon]
Name: AVERAGE.ACCT.AGE, Length: 233154, dtype: object

In [26]:
df['AVERAGE.ACCT.AGE.months'] =  df['AVERAGE.ACCT.AGE'].str.split().apply(lambda row: int(row[0].strip('yrs'))*12
                                                                                    + int(row[1].strip('mon')))

In [27]:
df[['AVERAGE.ACCT.AGE','AVERAGE.ACCT.AGE.months']].head()

         AVERAGE.ACCT.AGE  AVERAGE.ACCT.AGE.months
UniqueID
420825          0yrs 0mon                        0
537409         1yrs 11mon                       23
417566          0yrs 0mon                        0
624493          0yrs 8mon                        8
539055          0yrs 0mon                        0

<h2>Finding the relationships</h2>

In [28]:
# For any non-numeric data type columns in the dataframe, it is ignored. 
df.corr()

,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,State_ID,Employee_code_ID,MobileNo_Avl_Flag,...,SEC.SANCTIONED.AMOUNT,SEC.DISBURSED.AMOUNT,PRIMARY.INSTAL.AMT,SEC.INSTAL.AMT,NEW.ACCTS.IN.LAST.SIX.MONTHS,DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS,NO.OF_INQUIRIES,loan_default,Employment.Type.Numeric,AVERAGE.ACCT.AGE.months
disbursed_amount,1.000000,0.752668,0.376747,0.018328,0.078596,0.095203,0.068540,-0.023956,0.010120,NaN,...,-0.005271,-0.005119,0.002350,-0.005525,0.035880,0.020198,0.038513,0.077675,0.005300,0.004205
asset_cost,0.752668,1.000000,-0.301188,0.018586,0.150002,-0.005256,0.275878,-0.026348,0.008711,NaN,...,-0.010776,-0.010594,-0.004356,-0.005738,-0.021968,-0.007932,-0.017301,0.014261,0.080863,-0.015614
ltv,0.376747,-0.301188,1.000000,0.006382,-0.103732,0.121003,-0.300112,0.004882,0.004940,NaN,...,0.008800,0.008733,0.007358,0.000481,0.083824,0.041921,0.085725,0.098208,-0.106681,0.029853
branch_id,0.018328,0.018586,0.006382,1.000000,0.225744,-0.049957,0.048192,0.187782,0.088764,NaN,...,0.002404,0.002457,0.004955,0.004265,-0.008354,-0.001730,-0.001813,0.030193,-0.021243,0.005338
supplier_id,0.078596,0.150002,-0.103732,0.225744,1.000000,-0.063916,0.187401,0.105502,0.095792,NaN,...,-0.010175,-0.010031,-0.011953,-0.005826,-0.053264,-0.024622,-0.030988,0.027357,0.072066,-0.034095
manufacturer_id,0.095203,-0.005256,0.121003,-0.049957,-0.063916,1.000000,-0.104349,0.026412,-0.045009,NaN,...,0.003206,0.003301,0.014116,0.003020,0.050079,0.019438,0.010012,-0.025039,-0.037311,0.042522
Current_pincode_ID,0.068540,0.275878,-0.300112,0.048192,0.187401,-0.104349,1.000000,0.047903,-0.042609,NaN,...,-0.026059,-0.025630,0.002275,-0.006305,-0.100080,-0.057419,-0.058821,0.028419,0.203651,-0.062704
State_ID,-0.023956,-0.026348,0.004882,0.187782,0.105502,0.026412,0.047903,1.000000,0.117309,NaN,...,0.017842,0.017651,0.015843,0.009850,-0.014942,-0.000655,-0.016129,0.048075,-0.031541,-0.008205
Employee_code_ID,0.010120,0.008711,0.004940,0.088764,0.095792,-0.045009,-0.042609,0.117309,1.000000,NaN,...,-0.002259,-0.002224,0.013470,0.001894,0.005473,0.003624,-0.002108,0.020657,0.031426,0.000297
MobileNo_Avl_Flag,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aadhar_flag,-0.015589,-0.093716,0.106953,-0.036384,-0.081161,0.041251,-0.309285,-0.169882,0.048759,NaN,...,0.007591,0.007540,0.014832,0.006273,0.059269,0.023823,0.027317,-0.041593,-0.058794,0.012217
PAN_flag,0.014490,0.048075,-0.037786,0.030206,0.036804,-0.029272,0.041118,0.113939,-0.027579,NaN,...,0.015279,0.014907,-0.010851,-0.000219,0.007046,-0.002562,0.016657,0.002046,-0.014600,0.015093
VoterID_flag,0.011665,0.083899,-0.098393,0.021387,0.079355,-0.046489,0.281934,0.151839,-0.047342,NaN,...,-0.006619,-0.006580,-0.018820,-0.006019,-0.059591,-0.027453,-0.018285,0.043747,0.062433,-0.019884
Driving_flag,0.001381,0.020484,-0.024060,-0.015503,-0.015682,0.004777,0.039667,0.027886,-0.017617,NaN,...,0.002600,0.002583,0.006219,-0.000843,-0.000929,0.011311,-0.021179,-0.005821,-0.005205,0.017688
Passport_flag,0.008291,0.005542,0.004467,-0.008537,-0.008773,0.016338,-0.008913,-0.000915,-0.007205,NaN,...,0.003539,0.003506,0.012914,0.000524,0.008052,0.006695,-0.001908,-0.007602,-0.005094,0.015182
PERFORM_CNS.SCORE,0.011409,-0.047398,0.084993,-0.018049,-0.077029,0.073012,-0.161664,-0.042323,-0.005767,NaN,...,0.024365,0.023953,0.071309,0.015655,0.346025,0.164745,0.152838,-0.057929,-0.065804,0.474734
PRI.NO.OF.ACCTS,0.034461,-0.026798,0.086571,-0.010384,-0.070536,0.068371,-0.084687,-0.008704,0.009197,NaN,...,0.024877,0.024551,0.269546,0.023421,0.537622,0.314148,0.180744,-0.035456,-0.004993,0.234612
PRI.ACTIVE.ACCTS,0.039542,-0.021692,0.087929,-0.006403,-0.066930,0.065589,-0.117882,-0.021061,0.006111,NaN,...,0.026805,0.026325,0.192397,0.021210,0.702943,0.382584,0.195484,-0.041451,-0.025422,0.295723
PRI.OVERDUE.ACCTS,0.019422,-0.014782,0.051770,-0.005546,-0.042692,0.025992,-0.062177,-0.012381,-0.000116,NaN,...,0.017194,0.016855,0.103095,0.009324,0.109896,0.471564,0.063780,0.040872,0.009134,0.313213
PRI.CURRENT.BALANCE,0.015713,-0.004356,0.026714,-0.004133,-0.022582,0.031722,-0.055948,-0.006359,0.003528,NaN,...,0.021179,0.021152,0.152499,0.006799,0.198566,0.244243,0.023861,-0.027386,0.011260,0.146973
PRI.SANCTIONED.AMOUNT,0.006294,-0.001180,0.009955,-0.003370,-0.012959,0.017242,-0.025843,-0.004304,-0.001105,NaN,...,0.011859,0.011843,0.072591,0.003883,0.095074,0.122028,0.010743,-0.011304,0.007052,0.083567
PRI.DISBURSED.AMOUNT,0.006412,-0.001221,0.010177,-0.003412,-0.012950,0.017080,-0.025697,-0.004129,-0.001088,NaN,...,0.011771,0.011757,0.073058,0.003806,0.094681,0.122650,0.010935,-0.011155,0.007305,0.083373
SEC.NO.OF.ACCTS,-0.014916,-0.022600,0.013019,-0.003194,-0.025809,0.008392,-0.051766,0.031245,-0.001385,NaN,...,0.359193,0.353330,0.009986,0.235277,0.119791,0.100321,0.005035,-0.008385,-0.007784,0.073349
SEC.ACTIVE.ACCTS,-0.014275,-0.020359,0.010565,-0.001957,-0.019885,0.005898,-0.049852,0.032142,-0.003331,NaN,...,0.452693,0.445950,0.007063,0.148895,0.134577,0.109194,0.004830,-0.005993,-0.008243,0.073696
SEC.OVERDUE.ACCTS,-0.007305,-0.013455,0.010256,-0.007104,-0.015665,0.008152,-0.036228,0.015679,-0.006537,NaN,...,0.234422,0.230982,0.002066,0.077731,0.057046,0.108810,0.004975,-0.001371,-0.002778,0.075291
SEC.CURRENT.BALANCE,-0.004227,-0.008697,0.007195,0.001418,-0.008729,0.003106,-0.021048,0.013231,-0.003543,NaN,...,0.929196,0.929995,0.010393,0.096351,0.046465,0.044987,0.002715,-0.005531,-0.003346,0.028704
SEC.SANCTIONED.AMOUNT,-0.005271,-0.010776,0.008800,0.002404,-0.010175,0.003206,-0.026059,0.017842,-0.002259,NaN,...,1.000000,0.999646,0.011448,0.113395,0.055801,0.055198,0.002675,-0.006354,-0.004312,0.037574
SEC.DISBURSED.AMOUNT,-0.005119,-0.010594,0.008733,0.002457,-0.010031,0.003301,-0.025630,0.017651,-0.002224,NaN,...,0.999646,1.000000,0.011469,0.112880,0.054886,0.054374,0.002581,-0.006248,-0.004315,0.037020
PRIMARY.INSTAL.AMT,0.002350,-0.004356,0.007358,0.004955,-0.011953,0.014116,0.002275,0.015843,0.013470,NaN,...,0.011448,0.011469,1.000000,0.010849,0.127796,0.090364,0.008967,-0.010616,0.013409,0.039689
SEC.INSTAL.AMT,-0.005525,-0.005738,0.000481,0.004265,-0.005826,0.003020,-0.006305,0.009850,0.001894,NaN,...,0.113395,0.112880,0.010849,1.000000,0.028160,0.018613,0.002736,-0.001548,-0.005144,0.012456
NEW.ACCTS.IN.LAST.SIX.MONTHS,0.035880,-0.021968,0.083824,-0.008354,-0.053264,0.050079,-0.100080,-0.014942,0.005473,NaN,...,0.055801,0.054886,0.127796,0.028160,1.000000,0.182769,0.264709,-0.029400,-0.020828,0.033372
DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS,0.020198,-0.007932,0.041921,-0.001730,-0.024622,0.019438,-0.057419,-0.000655,0.003624,NaN,...,0.055198,0.054374,0.090364,0.018613,0.182769,1.000000,0.070715,0.034462,-0.001633,0.171348
NO.OF_INQUIRIES,0.038513,-0.017301,0.085725,-0.001813,-0.030988,0.010012,-0.058821,-0.016129,-0.002108,NaN,...,0.002675,0.002581,0.008967,0.002736,0.264709,0.070715,1.000000,0.043678,-0.006353,0.024883
loan_default,0.077675,0.014261,0.098208,0.030193,0.027357,-0.025039,0.028419,0.048075,0.020657,NaN,...,-0.006354,-0.006248,-0.010616,-0.001548,-0.029400,0.034462,0.043678,1.000000,0.024823,-0.024781
Employment.Type.Numeric,0.005300,0.080863,-0.106681,-0.021243,0.072066,-0.037311,0.203651,-0.031541,0.031426,NaN,...,-0.004312,-0.004315,0.013409,-0.005144,-0.020828,-0.001633,-0.006353,0.024823,1.000000,-0.018974
AVERAGE.ACCT.AGE.months,0.004205,-0.015614,0.029853,0.005338,-0.034095,0.042522,-0.062704,-0.008205,0.000297,NaN,...,0.037574,0.037020,0.039689,0.012456,0.033372,0.171348,0.024883,-0.024781,-0.018974,1.000000

In [37]:
cm = sns.light_palette("seagreen", as_cmap=True)

s = df.corr().style.background_gradient(cmap=cm)

s

In [31]:
df['MobileNo_Avl_Flag'].head()

UniqueID
420825    1
537409    1
417566    1
624493    1
539055    1
Name: MobileNo_Avl_Flag, dtype: int64

<mark>Try to plot all columns across each other and across multiple others according to their datatype. Like there must be specific plot to use for visualizing string data (categories) vs other types</mark>